export const EVENT_ACTIONS_TYPES = {
  GET_START: "GET_START",
  GET_SUCCESS: "GET_SUCCESS",
  GET_ERROR: "GET_ERROR",
  GET_END: "GET_END",
  ADD_SCHEDULE: "ADD_SCHEDULE",
  ADD_RESTAURANT: "ADD_RESTAURANT",
  REMOVE_ADDED_RESTAURANT: "REMOVE_ADDED_RESTAURANT",
  REMOVE_ADDED_SCHEDULE: "REMOVE_ADDED_SCHEDULE",
  ADD_PARTICIPANT: "ADD_PARTICIPANT",
};
